
service: first-sls-project
provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: ap-south-1
  role: arn:aws:iam::282049223824:role/serverless-code-build-role

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get
        